models:
    - ../model/checkpoint_seq2seq_wmtende_mt_best.npz
vocabs:
    - ../model/vocab.src.yml
    - ../model/vocab.tgt.yml
enc-depth: 6
dec-depth: 6
dim-emb: 512
transformer-dim-ffn: 2048
transformer-heads: 8
share-all-embed: True                  ## wheather share source embedding and target embedding
share-out-embed: True                  ## wheather share target embedding and projrct embedding
transformer-ffn-activation: relu
normalize-before: True                 ## wheather pre-norm or post-norm
learned-pos: True
max-seq-length: 512
use-emb-scale: False
transformer-ffn-depth: 1
normalize: 0.6
decode-length: 50
early-stop: True
use-fp16: True
n-best: True

devices:
    - 0
mini-batch: 16
beam-size: 4

#trace - debug - info - warn - err(or) - critical - off
log-level: trace
 
